In [1]:
import pandas as pd
import numpy as np

In [2]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://bwgkklxt:YJZU5TaU9b1zK9AvCDQmZ0G3kkYhrcTh@hattie.db.elephantsql.com/bwgkklxt')

In [3]:
def select(sql):
    return pd.read_sql(sql, con)

## 1 Exercise

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd


In [4]:
sql = '''
SELECT t.model,
       t.speed,
       t.hd
FROM PC AS t
WHERE t.price < 500'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

## 2 Exercise

In [5]:
sql = '''
SELECT DISTINCT t.maker
FROM Product AS t
WHERE t.type = 'Printer'
'''
select(sql)

maker
0     A
1     D
2     E

## 3 Exercise

In [6]:
sql = '''
SELECT t.model,
       t.ram,
       t.screen
FROM Laptop AS t
WHERE t.price > 1000'''
select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

## 4 Exercise

In [7]:
sql = '''SELECT t.*
FROM Printer AS t
WHERE t.color = 'y'
'''
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

## 5 Exercise

In [8]:
sql = '''
SELECT t.model,
       t.speed,
       t.hd
FROM PC AS t
WHERE t.cd in ('12x','24x')
  AND t.price < 600
'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

## 6 Exercise

In [9]:
sql = '''
SELECT DISTINCT p.maker,
       t.speed
FROM Laptop AS t
JOIN Product AS p ON t.model = p.model
WHERE t.hd >= 10
'''
select(sql)

maker  speed
0     A    750
1     A    450
2     A    600
3     B    750

## 7 Exercise

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).


In [10]:
sql = '''select distinct t.model, p.price from Product as t
join PC as p on t.model = p.model
where t.maker = 'B'

union all
select distinct t.model, l.price from Product as t
join Laptop as l on l.model = t.model
where t.maker = 'B'
'''
select(sql)

model   price
0  1121   850.0
1  1750  1200.0

## 8 Exercise

Найдите производителя, выпускающего ПК, но не ПК-блокноты.

In [11]:
sql = '''
WITH pc_makers AS
  (SELECT DISTINCT t.maker
   FROM Product AS t
   WHERE t.type = 'PC'),
     laptop_makers AS
  (SELECT DISTINCT t.maker
   FROM product AS t
   WHERE t.type = 'Laptop')
SELECT p.*
FROM pc_makers AS p
WHERE p.maker not in
    (SELECT *
     FROM laptop_makers)
'''
select(sql)

maker
0     E

##### Лучший способ (Except | Intersect)

In [12]:
sql = '''
SELECT DISTINCT maker
FROM Product
WHERE type = 'PC'
EXCEPT
SELECT DISTINCT product.maker
FROM Product
Where type = 'Laptop'
'''
select(sql)

maker
0     E

## 9 Exercise

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker


In [13]:
sql = '''
SELECT DISTINCT t.maker
FROM Product AS t
JOIN pc AS p ON t.model = p.model
WHERE p.speed >= 450
'''
select(sql)

maker
0     B
1     E
2     A

## 10 Exercise

Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price


In [14]:
sql = '''
WITH printer_max_price AS
  (SELECT max(t.price)
   FROM Printer AS t)
SELECT t.model,
       t.price
FROM Printer AS t
WHERE t.price =
    (SELECT *
     FROM printer_max_price)
'''
select(sql)

model  price
0  1276  400.0
1  1288  400.0

## 11 Exercise

Найдите среднюю скорость ПК.

In [15]:
sql = '''
SELECT avg(t.speed) AS speed_avg
FROM PC AS t
'''
select(sql)

speed_avg
0  608.333333

## 12 Exercise

Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.


In [16]:
sql = '''
SELECT avg(t.speed) AS speed_avg
FROM Laptop AS t
WHERE t.price > 1000
'''
select(sql)

speed_avg
0      700.0

## 13 Exercise

Найдите среднюю скорость ПК, выпущенных производителем A.

In [17]:
sql = '''
SELECT avg(t.speed) AS speed_avg
FROM PC AS t
JOIN Product AS p ON p.model = t.model
WHERE p.maker = 'A'
'''
select(sql)

speed_avg
0     606.25

## 14 Exercise

Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.


In [18]:
sql = '''
SELECT s.class,
       s.name,
       c.country
FROM Ships AS s
JOIN Classes AS c ON s.class = c.class
WHERE c.numguns >= 10'''
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

## 15 Exercise

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [19]:
sql = '''
SELECT t.hd
FROM PC AS t
GROUP BY t.hd
HAVING count(1) > 1
'''
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

## 16 Exercise

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

In [20]:
sql = '''
SELECT DISTINCT t.model,
                l.model,
                t.speed,
                t.ram
FROM pc AS t,
     pc AS l
WHERE t.speed = l.speed
  AND t.ram = l.ram
  AND t.model > l.model
ORDER BY t.model DESC,
         l.model
'''
select(sql)

model model  speed  ram
0  1260  1232    500   32
1  1233  1121    750  128
2  1233  1232    500   64

## 17 Exercise

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed

In [21]:
sql = '''
SELECT DISTINCT p.type,
                t.model,
                t.speed
FROM Laptop AS t
JOIN Product AS p ON t.model = p.model
WHERE t.speed <
    (SELECT min(pc.speed)
     FROM pc)
'''
select(sql)

type model  speed
0  Laptop  1298    350

## 18 Exercise

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [22]:
sql = '''
with printer_product as (
select t.*, p.maker from Printer as t
join Product as p on t.model = p.model
where color = 'y')

select distinct t.maker, t.price from printer_product as t
where t.price = (select min(t.price) from printer_product as t)

'''
select(sql)

maker  price
0     D  270.0

In [23]:
sql = '''
WITH printer_product AS
  (SELECT t.*,
          p.maker
   FROM Printer AS t
   JOIN Product AS p ON t.model = p.model
   WHERE color = 'y')
SELECT DISTINCT t.maker,
                t.price
FROM printer_product AS t
WHERE t.price =
    (SELECT min(t.price)
     FROM printer_product AS t)
'''
select(sql)

maker  price
0     D  270.0

## 19 Exercise

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [24]:
sql = '''
SELECT p.maker,
       avg(t.screen) AS screen_avg
FROM Laptop AS t
JOIN Product AS p ON t.model = p.model
GROUP BY p.maker
'''
select(sql)

maker  screen_avg
0     B        14.0
1     C        12.0
2     A        13.0

## 20 Exercise

Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [25]:
sql = '''
SELECT t.maker,
       count(1) AS models_cnt
FROM product AS t
WHERE t.type = 'PC'
GROUP BY t.maker
HAVING count(1) > 2
'''
select(sql)

maker  models_cnt
0     E           3

## 21 Exercise

Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [26]:
sql = '''
SELECT p.maker,
       max(t.price) AS price_max
FROM pc AS t
JOIN Product AS p ON t.model = p.model
GROUP BY p.maker
'''
select(sql)

maker  price_max
0     B      850.0
1     E      350.0
2     A      980.0

## 22 Exercise

Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [27]:
sql = '''
SELECT t.speed,
       avg(t.price) AS price_avg
FROM PC AS t
WHERE t.speed > 600
GROUP BY t.speed'''
select(sql)

speed  price_avg
0    900      980.0
1    750      900.0
2    800      970.0

## 23 Exercise

Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker

In [28]:
sql = '''
SELECT DISTINCT p.maker
FROM PC AS t
JOIN Product AS p ON t.model = p.model
WHERE t.speed >= 750 INTERSECT
  SELECT DISTINCT p.maker
  FROM Laptop AS t
  JOIN Product AS p ON t.model = p.model WHERE t.speed >= 750
'''
select(sql)

maker
0     B
1     A

## 24 Exercise

Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [29]:
sql = '''
WITH model_price AS
  (SELECT t.model,
          t.price
   FROM pc AS t
   UNION ALL SELECT l.model,
                    l.price
   FROM laptop AS l
   UNION ALL SELECT p.model,
                    p.price
   FROM printer AS p)
SELECT DISTINCT t.model
FROM model_price AS t
WHERE t.price =
    (SELECT max(t.price)
     FROM model_price AS t)'''
select(sql)

model
0  1750

In [30]:
sql = '''
with model_price as (
select t.model, t.price from pc as t
union all
select l.model, l.price from laptop as l
union all
select p.model, p.price from printer as p)

select distinct t.model from model_price as t
where t.price = (select max(t.price) from model_price as t)
'''
select(sql)

model
0  1750

## 25 Exercise

Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker


In [31]:
sql = '''
with pc_model_min_ram as (
select t.* from pc as t
where t.ram = (select min(t.ram) from pc as t)),

pc_top_speed as (
select t.* from pc_model_min_ram as t
where t.speed = (select max(t.speed) from pc_model_min_ram as t)),

pc_top_speed_makers as (select p.maker from pc_top_speed as t
join Product as p on t.model = p.model)

select distinct t.maker from product as t
where t.type = 'Printer' and t.maker in (select * from pc_top_speed_makers)
'''
select(sql)

maker
0     A
1     E

In [32]:
sql = '''
WITH pc_model_min_ram AS
  (SELECT t.*
   FROM pc AS t
   WHERE t.ram =
       (SELECT min(t.ram)
        FROM pc AS t)),
     pc_top_speed AS
  (SELECT t.*
   FROM pc_model_min_ram AS t
   WHERE t.speed =
       (SELECT max(t.speed)
        FROM pc_model_min_ram AS t)),
     pc_top_speed_makers AS
  (SELECT p.maker
   FROM pc_top_speed AS t
   JOIN Product AS p ON t.model = p.model)

SELECT DISTINCT t.maker
FROM product AS t
WHERE t.type = 'Printer'
  AND t.maker in
    (SELECT *
     FROM pc_top_speed_makers)
'''
select(sql)

maker
0     A
1     E

## 26 Exercise

Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [33]:
sql = '''
with pc_laptop_prices as (
select t.price from PC as t
join Product as p on t.model = p.model
where p.maker = 'A'
union all
select l.price from Laptop as l
join Product as p on l.model = p.model
where p.maker = 'A')

select avg(t.price) as price_avg from pc_laptop_prices as t

'''
select(sql)

price_avg
0  754.166667

In [34]:
sql = '''
WITH pc_laptop_prices AS
  (SELECT t.price
   FROM PC AS t
   JOIN Product AS p ON t.model = p.model
   WHERE p.maker = 'A'
   UNION ALL SELECT l.price
   FROM Laptop AS l
   JOIN Product AS p ON l.model = p.model
   WHERE p.maker = 'A')
SELECT avg(t.price) AS price_avg
FROM pc_laptop_prices AS t
'''
select(sql)

price_avg
0  754.166667

## 27 Exercise

Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.

In [35]:
sql = '''
with printer_makers as (
select distinct t.maker from Product as t
where t.type =  'Printer')

select p.maker, avg(t.hd) as hd_avg from PC as t
join Product as p on t.model = p.model
where p.maker in (select * from printer_makers)
group by p.maker
'''
select(sql)

maker  hd_avg
0     E   10.00
1     A   14.75

In [36]:
sql = '''
WITH printer_makers AS
  (SELECT DISTINCT t.maker
   FROM Product AS t
   WHERE t.type = 'Printer')
SELECT p.maker,
       avg(t.hd) AS hd_avg
FROM PC AS t
JOIN Product AS p ON t.model = p.model
WHERE p.maker in
    (SELECT *
     FROM printer_makers)
GROUP BY p.maker
'''
select(sql)

maker  hd_avg
0     E   10.00
1     A   14.75

## 28 Exercise

Используя таблицу Product, определить количество производителей, выпускающих по одной модели.

In [37]:
sql = '''
WITH makers_one_model AS
  (SELECT t.maker,
          count(1) AS model_cnt
   FROM Product AS t
   GROUP BY t.maker
   HAVING count(1) = 1)
SELECT count(1)
FROM makers_one_model AS t
'''
select(sql)

count
0      1

## 29 Exercise

В предположении, что приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)], написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o.

In [38]:
sql = '''
select 
case when i.point is not null then i.point else o.point end as point,
case when i.date is not null then i.date else o.date end as date,
i.inc,
o.out
from income_o as i
full join outcome_o as o on i.date = o.date and i.point = o.point
'''
select(sql)

point       date      inc       out
0       1 2001-03-22  15000.0       NaN
1       1 2001-03-23  15000.0       NaN
2       1 2001-03-24   3400.0   3663.00
3       1 2001-04-13   5000.0   4490.00
4       1 2001-05-11   4500.0   2530.00
5       2 2001-03-22  10000.0   1440.00
6       2 2001-03-24   1500.0       NaN
7       3 2001-09-13  11500.0   1500.00
8       3 2001-10-02  18000.0       NaN
9       3 2002-09-16      NaN   2150.00
10      2 2001-03-29      NaN   7848.00
11      3 2001-09-14      NaN   2300.00
12      1 2001-03-14      NaN  15348.00
13      1 2001-03-29      NaN   2004.00
14      1 2001-04-11      NaN   3195.04
15      2 2001-04-02      NaN   2040.00
16      1 2001-04-27      NaN   3110.00
17      1 2001-03-28      NaN   2075.00
18      1 2001-03-26      NaN   1221.00

In [39]:
sql = '''
SELECT CASE
           WHEN i.point IS NOT NULL THEN i.point
           ELSE o.point
       END AS POINT,
       CASE
           WHEN i.date IS NOT NULL THEN i.date
           ELSE o.date
       END AS date,
       i.inc,
       o.out
FROM income_o AS i
FULL JOIN outcome_o AS o ON i.date = o.date
AND i.point = o.point
'''
select(sql)

point       date      inc       out
0       1 2001-03-22  15000.0       NaN
1       1 2001-03-23  15000.0       NaN
2       1 2001-03-24   3400.0   3663.00
3       1 2001-04-13   5000.0   4490.00
4       1 2001-05-11   4500.0   2530.00
5       2 2001-03-22  10000.0   1440.00
6       2 2001-03-24   1500.0       NaN
7       3 2001-09-13  11500.0   1500.00
8       3 2001-10-02  18000.0       NaN
9       3 2002-09-16      NaN   2150.00
10      2 2001-03-29      NaN   7848.00
11      3 2001-09-14      NaN   2300.00
12      1 2001-03-14      NaN  15348.00
13      1 2001-03-29      NaN   2004.00
14      1 2001-04-11      NaN   3195.04
15      2 2001-04-02      NaN   2040.00
16      1 2001-04-27      NaN   3110.00
17      1 2001-03-28      NaN   2075.00
18      1 2001-03-26      NaN   1221.00

## 30 Exercise

В предположении, что приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code), требуется получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.
Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc). Отсутствующие значения считать неопределенными (NULL).

In [40]:
sql = '''
with income_agg_table as (select i.point,
i.date,
sum(i.inc) as inc_sum
from income as i
group by i.point, i.date),

outcome_agg_table as (select o.point,
o.date,
sum(o.out) as out_sum
from outcome as o
group by o.point, o.date
)

select 
case when i.point is not null then i.point else o.point end as point,
case when i.date is not null then i.date else o.date end as date,
o.out_sum,
i.inc_sum
from outcome_agg_table as o
full join income_agg_table as i on o.date = i.date and o.point = i.point
'''
select(sql)

point       date   out_sum  inc_sum
0       1 2001-03-24   7163.00   7000.0
1       1 2001-05-11   2530.00   4500.0
2       1 2001-04-11   3195.04      NaN
3       3 2001-09-14   1150.00      NaN
4       1 2001-03-26   1221.00      NaN
5       1 2001-03-29   4010.00      NaN
6       2 2001-04-02   2040.00      NaN
7       3 2001-09-13   2700.00   3100.0
8       1 2001-04-27   3110.00      NaN
9       1 2001-03-28   2075.00      NaN
10      1 2001-03-14  15348.00      NaN
11      2 2001-03-22   2880.00  10000.0
12      2 2001-03-29   7848.00      NaN
13      1 2001-04-13   4490.00  10000.0
14      1 2001-03-23       NaN  15000.0
15      1 2001-03-22       NaN  30000.0
16      2 2001-03-24       NaN   3000.0